RedditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new]
  resource :session, only: [:create, :new, :destroy]
  resources :subs do
    resources :posts, only: [:create, :new]
  end
  resources :posts, only: [:edit, :update, :show, :destroy]
end

RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditClone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs,
    foreign_key: :post_id,
    class_name: :PostSub

  has_many :subs, through: :post_subs, source: :sub

end

RedditClone/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :bigint(8)        not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord
  belongs_to :post,
    foreign_key: :post_id,
    class_name: :Post

  belongs_to :sub,
    foreign_key: :sub_id,
    class_name: :Sub
end

RedditClone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, :moderator_id, presence: true

  belongs_to :moderator,
  foreign_key: :moderator_id,
  class_name: :User

  has_many :post_subs,
    foreign_key: :sub_id,
    class_name: :PostSub

  has_many :posts, through: :post_subs, source: :post

end

RedditClone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :password, length: { minimum: 6, allow_nil: true}
  validates :username, :session_token, :password_digest, presence: true
  after_initialize :ensure_session_token
  
  attr_reader :password
  
  has_many :subs,
  foreign_key: :moderator_id,
  class_name: :Sub
  
  has_many :posts,
    foreign_key: :author_id,
    class_name: :Post
  
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil 
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end 
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
  
end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :signed_in?, :current_user
  
  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end
  
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def sign_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def signed_in?
    !!current_user
  end
  
  def require_signed_in
    redirect_to new_session_url unless signed_in?
  end
end

RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_signed_in
  before_action :require_author, only: [:edit, :update]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    # @post.sub_id = params[:sub_id]
    @post.author_id = current_user.id

    if @post.save
      redirect_to sub_url(@post.sub_id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def require_author
    @post = Post.find(params[:id])
    if @post.author_id != current_user.id
      flash[:errors] = ['You are not the author of this post']
      redirect_to post_url(@post)
    end
  end

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all

  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub_url)
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      sign_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ['Invalid creds']
      render :new
    end
  end
  
  def destroy
    sign_out
    redirect_to new_session_url
  end
end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_signed_in
  before_action :require_moderator, only: [:edit, :update]

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
        @subs = Sub.all
  end

  def index
    @subs = Sub.all
  end

  def require_moderator
    @sub = Sub.find(params[:id])
    redirect_to sub_url(@sub) unless current_user.id == @sub.moderator_id
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    
    if @user.save
      sign_in(@user)
      redirect_to subs_url
    else 
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end 
  
  def new 
    @user = User.new
  end 
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end 
end

RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

RedditClone/app/helpers/session_helper.rb
module SessionHelper
end

RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if signed_in? %>
      Welcome, <%= current_user.username %>!
      <form class="" action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <button type="submit" name="sign out">Sign Out</button>
      </form>
    <% end %>

    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <%= error %>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

RedditClone/app/views/posts/edit.html.erb
<!-- post edit  -->

<h2>Edit Post</h2>

<form action="<%= post_url(@post) %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="hidden" name="_method" value="patch">
<label>Title:
  <input type="text" name="post[title]"></label>
  <br>

  <label>Content:
  <input type="text" name="post[content]"></label>
  <br>

<label>URL:
  <input type="text" name="post[url]"></label>
  <br>
    <% @subs.each do |sub|%>
<label>
  <input type="checkbox" name="post[sub_ids][]" value= "<%= sub.id %>"> <%= sub.title %> </label>
    <% end %>
  <input type="submit" name="" value="Edit Post"
</form>

RedditClone/app/views/posts/show.html.erb
<!-- post show -->
<h1><%= @post.title %></h1>
<% if @post.url %>
URL: <%= @post.url %>
<br>
<% end %>

<% if @post.content %>
Post Contents: <%= @post.content %>
<br>
<% end %>

Posted in: <%= @post.sub.title %>
<br>
Author: <%= @post.author.username %>

<br>
<a href="<%= edit_post_url(@post) %>">Edit Post</a>

RedditClone/app/views/subs/edit.html.erb
<!-- sub edit -->


<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" 
  value="<%= form_authenticity_token %>">
  
  <label>Title:
  <input type="text" name="sub[title]" value="<%= @sub.title %>"></label>
  <br>
  <label>Description:
  <input type="text" name="sub[description]" value="<%= @sub.description %>"></label>
  <br>
  <button type="submit" name="button">Edit Sub</button>
</form>

RedditClone/app/views/subs/index.html.erb
<h1>All Subs</h1>
<ul>
  
<% @subs.each do |sub| %>
  <li>
    <a href="<%= sub_url(sub) %>"> r/<%= sub.title %></a>
  </li>
<% end %>
</ul>

RedditClone/app/views/subs/new.html.erb
<!-- sub new  -->

<h1>New Sub</h1>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" 
  value="<%= form_authenticity_token %>">
  
  <label>Title:
  <input type="text" name="sub[title]" value=""></label>
  <br>
  <label>Description:
  <input type="text" name="sub[description]" value=""></label>
  <br>
  <button type="submit" name="button">New Sub</button>
</form>

RedditClone/app/views/subs/show.html.erb
<!-- subs show -->
<h2>r/<%= @sub.title.capitalize %></h2>
Moderator: <%= @sub.moderator.username.capitalize %>
<br>
Description: <%= @sub.description %>

<br>
<a href="<%= edit_sub_url(@sub)  %>">Edit</a>

<ul><% @sub.posts.each do |post| %>
  <li><a href="<%= post_url(post) %>"><%= post.title %></a></li>
<% end %>
</ul>
<!-- post new  -->
<h1>New Post</h1>

<form action="<%= sub_posts_url(@sub)%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title:
  <input type="text" name="post[title]"></label>
  <br>
  <label>Content:
  <input type="text" name="post[content]"></label>
  <br>
  <label>URL:
  <input type="text" name="post[url]"></label>
  <br>
  <% @subs.each do |sub|%>
<label>
<input type="checkbox" name="post[sub_ids][]" value= "<%= sub.id %>"> <%= sub.title %> </label>
  <% end %>
  <br>
  <input type="submit" name="" value="Create Post">
</form>

RedditClone/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Username
    <input type="text" name="user[username]" value="">
  </label>
  
  <label>
    Password
    <input type="password" name="user[password]" value="">
  </label>
  
  <input type="submit" name="" value="Sign Up">
  
</form>